cd "e:/Kendryte_my/SPI_st7789v/build"
SET ALLUSERSPROFILE=C:\ProgramData
SET ALTERAOCLSDKROOT=D:\altera\hld
SET APPDATA=C:\Users\acer\AppData\Roaming
SET CommonProgramFiles=C:\Program Files\Common Files
SET CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
SET CommonProgramW6432=C:\Program Files\Common Files
SET COMPUTERNAME=LAPTOP-JNLJ2B4J
SET ComSpec=C:\WINDOWS\system32\cmd.exe
SET CUDA_BIN_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin
SET CUDA_LIB_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\lib\x64
SET CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1
SET CUDA_PATH_V10_0=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
SET CUDA_PATH_V10_1=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
SET CUDA_SDK_BIN_PATH=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v9.1\bin\win64
SET CUDA_SDK_LIB_PATH=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v9.1\common\lib\x64
SET CUDA_SDK_PATH=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v9.1
SET DriverData=C:\Windows\System32\Drivers\DriverData
SET FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
SET FPS_BROWSER_USER_PROFILE_STRING=Default
SET HOMEDRIVE=C:
SET HOMEPATH=\Users\acer
SET IDF_TOOLS_PATH=C:\Users\acer\.espressif
SET INTEL_DEV_REDIST=C:\Program Files (x86)\Common Files\Intel\Shared Libraries\
SET IWBPath=E:\SAP\iwb
SET KMP_DUPLICATE_LIB_OK=TRUE
SET LOCALAPPDATA=C:\Users\acer\AppData\Local
SET LOGONSERVER=\\LAPTOP-JNLJ2B4J
SET MGLS_LICENSE_FILE=E:\Modelsim\win64\LICENSE.TXT
SET MIC_LD_LIBRARY_PATH=C:\Program Files (x86)\Common Files\Intel\Shared Libraries\compiler\lib\mic
SET MKL_SERIAL=YES
SET NUMBER_OF_PROCESSORS=8
SET NVCUDASAMPLES10_0_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0
SET NVCUDASAMPLES10_1_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.1
SET NVCUDASAMPLES9_1_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v9.1
SET NVCUDASAMPLES_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v9.1
SET NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
SET OneDrive=C:\Users\acer\OneDrive
SET OS=Windows_NT
SET Path=e:\Kendryte_IDE\KendryteIDE\bin;e:\Kendryte_IDE\KendryteIDE\LocalPackage\toolchain\bin;e:\Kendryte_IDE\KendryteIDE\LocalPackage\cmake\bin;e:\Kendryte_IDE\KendryteIDE\LocalPackage\jlink;e:\Kendryte_IDE\KendryteIDE\LocalPackage\clang-format\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH
SET PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
SET PROCESSOR_ARCHITECTURE=AMD64
SET PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
SET PROCESSOR_LEVEL=6
SET PROCESSOR_REVISION=8e0a
SET ProgramData=C:\ProgramData
SET ProgramFiles=C:\Program Files
SET ProgramFiles(x86)=C:\Program Files (x86)
SET ProgramW6432=C:\Program Files
SET PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
SET PUBLIC=C:\Users\Public
SET PyCharm Community Edition=E:\pycharm\PyCharm Community Edition 2020.1.1\bin;
SET QSYS_ROOTDIR=D:\altera\quartus\sopc_builder\bin
SET QUARTUS_ROOTDIR=D:\altera\quartus
SET SESSIONNAME=Console
SET SNC_LIB=C:\Program Files (x86)\SAP\SNCEncryption\x86\sapsncencryption.dll
SET SNC_LIB_64=C:\Program Files (x86)\SAP\SNCEncryption\x64\sapsncencryption.dll
SET SOPC_KIT_NIOS2=D:\altera\nios2eds
SET SystemDrive=C:
SET SystemRoot=C:\WINDOWS
SET TEMP=C:\Users\acer\AppData\Local\Temp
SET TMP=C:\Users\acer\AppData\Local\Temp
SET TSK_OPTIONS_FILE_SW160800v6_3r1=C:\Program Files\TASKING\TriCore v6.3r1\etc\licopt.txt
SET USERDOMAIN=LAPTOP-JNLJ2B4J
SET USERDOMAIN_ROAMINGPROFILE=LAPTOP-JNLJ2B4J
SET USERNAME=月兮
SET USERPROFILE=C:\Users\acer
SET VS140COMNTOOLS=H:\VC_2015\Common7\Tools\
SET VSCODE_CWD=E:\Kendryte_IDE\KendryteIDE\Application\app_1.34.1-beta_20190802.2
SET VSCODE_IPC_HOOK=\\.\pipe\d555cd1063237951711aed29b17c6449-1.34.1-beta-main-sock
SET VSCODE_LOGS=E:\Kendryte_IDE\KendryteIDE\UserData\latest\user-data\logs\20220325T200542
SET VSCODE_NLS_CONFIG={"locale":"zh-cn","availableLanguages":{"*":"zh-cn"},"_languagePackId":"2ae16f5a9a23c98b985a67d503c3ac22.zh-cn","_translationsConfigFile":"E:\\Kendryte_IDE\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\tcf.json","_cacheRoot":"E:\\Kendryte_IDE\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn","_resolvedLanguagePackCoreLocation":"E:\\Kendryte_IDE\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\e4de46724de34a5f46541818e9fee25971ac9969","_corruptedFile":"E:\\Kendryte_IDE\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\corrupted.info","_languagePackSupport":true}
SET VSCODE_NODE_CACHED_DATA_DIR=E:\Kendryte_IDE\KendryteIDE\UserData\latest\user-data\CachedData\e4de46724de34a5f46541818e9fee25971ac9969
SET VSCODE_PID=9684
SET VSCODE_PORTABLE=E:\Kendryte_IDE\KendryteIDE\UserData\latest
SET windir=C:\WINDOWS
SET XILINX_FOR_ALTIUM_OVERRIDE= 
SET PYTHONHOME=e:/Kendryte_IDE/KendryteIDE/LocalPackage/python2library
SET PYTHONPATH=e:/Kendryte_IDE/KendryteIDE/LocalPackage/python2library;e:/Kendryte_IDE/KendryteIDE/LocalPackage/toolchain/share/gdb/python
SET PYTHONDONTWRITEBYTECODE=yes
SET CMAKE_MAKE_PROGRAM=make
SET KENDRYTE_IDE=yes
SET LANG=en_US.utf-8
"e:/Kendryte_IDE/KendryteIDE/LocalPackage/cmake/bin/cmake.exe" --build e:/Kendryte_my/SPI_st7789v/build -- -j 7